server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/kicksaura
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: prod
    show-sql: false
  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET}
  expiration: 1296000000 # 15 days in milliseconds

msg91:
  widget-id: ${MSG91_WIDGET_ID:36677868776e353439383633}
  widget-token: ${MSG91_WIDGET_TOKEN:}
  authkey: ${MSG91_AUTHKEY:}
