server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service:8081}
          predicates:
            - Path=/api/v1/users/**,/api/v1/internal/users/**,/api/users/**,/api/auth/**

        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://product-service:8082}
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**,/api/v1/brands/**,/api/v1/admin/products/**,/api/v1/admin/categories/**,/api/v1/admin/brands/**,/api/v1/reviews/**,/api/v1/admin/coupons/**

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://order-service:8083}
          predicates:
            - Path=/api/v1/orders/**,/api/v1/admin/orders/**

        - id: user-service-admin
          uri: ${USER_SERVICE_URL:http://user-service:8081}
          predicates:
            - Path=/api/v1/admin/users/**


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.springframework.cloud.gateway: INFO

jwt:
  secret: ${JWT_SECRET}